// Report export: CSV and a print-ready HTML report.
//
// We deliberately avoid a binary PDF library (pdfkit/puppeteer) — they pull in
// heavy/native deps that complicate cloud deploys. Instead we emit a clean,
// self-contained HTML report the browser can print to PDF (Cmd/Ctrl-P → Save
// as PDF). CSV is generated by hand to avoid a dependency.

export interface ExportBug {
  id: string;
  title: string;
  severity: string;
  type: string;
  status: string;
  url: string;
  assignedTo?: { email: string } | null;
  createdAt: Date | string;
}

export interface ExportRun {
  id: string;
  url: string;
  status: string;
  startedAt: Date | string;
  testsTotal: number;
  testsPassed: number;
  testsFailed: number;
}

// Escape a single CSV field per RFC 4180 (quote if it contains comma/quote/newline).
function csvField(value: unknown): string {
  const s = value == null ? "" : String(value);
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function bugsToCsv(bugs: ExportBug[]): string {
  const header = ["id", "title", "severity", "type", "status", "url", "assignedTo", "createdAt"];
  const rows = bugs.map((b) =>
    [
      b.id,
      b.title,
      b.severity,
      b.type,
      b.status,
      b.url,
      b.assignedTo?.email ?? "",
      typeof b.createdAt === "string" ? b.createdAt : b.createdAt.toISOString(),
    ]
      .map(csvField)
      .join(",")
  );
  return [header.join(","), ...rows].join("\r\n");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const SEVERITY_COLOR: Record<string, string> = {
  CRITICAL: "#dc2626",
  HIGH: "#ea580c",
  MEDIUM: "#ca8a04",
  LOW: "#65a30d",
};

// Build a self-contained HTML report (inline CSS) suitable for print-to-PDF.
export function buildHtmlReport(run: ExportRun, bugs: ExportBug[], projectName: string): string {
  const counts = bugs.reduce<Record<string, number>>((acc, b) => {
    acc[b.severity] = (acc[b.severity] ?? 0) + 1;
    return acc;
  }, {});
  const started = typeof run.startedAt === "string" ? run.startedAt : run.startedAt.toISOString();

  const rows = bugs
    .map(
      (b) => `
      <tr>
        <td><span class="sev" style="background:${SEVERITY_COLOR[b.severity] ?? "#666"}">${escapeHtml(b.severity)}</span></td>
        <td>${escapeHtml(b.type)}</td>
        <td>${escapeHtml(b.title)}</td>
        <td>${escapeHtml(b.status)}</td>
        <td>${escapeHtml(b.assignedTo?.email ?? "—")}</td>
      </tr>`
    )
    .join("");

  const summaryChips = Object.entries(counts)
    .map(
      ([sev, n]) =>
        `<span class="chip" style="border-color:${SEVERITY_COLOR[sev] ?? "#666"};color:${SEVERITY_COLOR[sev] ?? "#666"}">${escapeHtml(sev)}: ${n}</span>`
    )
    .join(" ");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>QA Report — ${escapeHtml(projectName)}</title>
<style>
  body{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#18181b;max-width:900px;margin:40px auto;padding:0 20px}
  h1{font-size:22px;margin:0 0 4px} .muted{color:#71717a;font-size:13px}
  .summary{margin:20px 0;padding:16px;background:#fafafa;border:1px solid #e4e4e7;border-radius:10px}
  .chip{display:inline-block;border:1px solid;border-radius:999px;padding:2px 10px;font-size:12px;font-weight:600;margin-right:6px}
  table{width:100%;border-collapse:collapse;margin-top:16px}
  th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #e4e4e7;font-size:13px;vertical-align:top}
  th{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#71717a}
  .sev{color:#fff;border-radius:5px;padding:1px 7px;font-size:11px;font-weight:700}
  @media print{body{margin:0}}
</style></head><body>
  <h1>QA Report — ${escapeHtml(projectName)}</h1>
  <div class="muted">Run ${escapeHtml(run.id)} · Target ${escapeHtml(run.url)} · ${escapeHtml(started)}</div>
  <div class="summary">
    <strong>${bugs.length}</strong> bug(s) found ·
    Tests: ${run.testsPassed}/${run.testsTotal} passed (${run.testsFailed} failed)<br><br>
    ${summaryChips || '<span class="muted">No bugs 🎉</span>'}
  </div>
  <table>
    <thead><tr><th>Severity</th><th>Type</th><th>Title</th><th>Status</th><th>Assignee</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5" class="muted">No bugs reported.</td></tr>'}</tbody>
  </table>
  <p class="muted" style="margin-top:30px">Generated by AI QA Engineer · Print to PDF with Cmd/Ctrl-P</p>
</body></html>`;
}
